// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Entity } from '../wrath-of-toldir/entity';
import { Item } from '../wrath-of-toldir/items/item';
import { PrivateStats } from '../wrath-of-toldir/private-stats';


export class Character {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Character {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCharacter(bb:flatbuffers.ByteBuffer, obj?:Character):Character {
  return (obj || new Character()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCharacter(bb:flatbuffers.ByteBuffer, obj?:Character):Character {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Character()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

player(obj?:Entity):Entity|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Entity()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

stats(obj?:PrivateStats):PrivateStats|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new PrivateStats()).__init(this.bb_pos + offset, this.bb!) : null;
}

gold():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

items(index: number, obj?:Item):Item|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Item()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

itemsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startCharacter(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addPlayer(builder:flatbuffers.Builder, playerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, playerOffset, 0);
}

static addStats(builder:flatbuffers.Builder, statsOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, statsOffset, 0);
}

static addGold(builder:flatbuffers.Builder, gold:number) {
  builder.addFieldInt32(3, gold, 0);
}

static addItems(builder:flatbuffers.Builder, itemsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, itemsOffset, 0);
}

static createItemsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startItemsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endCharacter(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
