// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Vec3 {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Vec3 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

x():number {
  return this.bb!.readInt16(this.bb_pos);
}

y():number {
  return this.bb!.readInt16(this.bb_pos + 2);
}

z():number {
  return this.bb!.readInt16(this.bb_pos + 4);
}

static sizeOf():number {
  return 6;
}

static createVec3(builder:flatbuffers.Builder, x: number, y: number, z: number):flatbuffers.Offset {
  builder.prep(2, 6);
  builder.writeInt16(z);
  builder.writeInt16(y);
  builder.writeInt16(x);
  return builder.offset();
}

}
