// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class TileSet {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):TileSet {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTileSet(bb:flatbuffers.ByteBuffer, obj?:TileSet):TileSet {
  return (obj || new TileSet()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTileSet(bb:flatbuffers.ByteBuffer, obj?:TileSet):TileSet {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TileSet()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

gid():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

static startTileSet(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static addGid(builder:flatbuffers.Builder, gid:number) {
  builder.addFieldInt16(1, gid, 0);
}

static endTileSet(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTileSet(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset, gid:number):flatbuffers.Offset {
  TileSet.startTileSet(builder);
  TileSet.addKey(builder, keyOffset);
  TileSet.addGid(builder, gid);
  return TileSet.endTileSet(builder);
}
}
