// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { EntityTexture } from '../../wrath-of-toldir/entity-texture';
import { Vec2 } from '../../wrath-of-toldir/vec2';


export class SpawnCommand {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):SpawnCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSpawnCommand(bb:flatbuffers.ByteBuffer, obj?:SpawnCommand):SpawnCommand {
  return (obj || new SpawnCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSpawnCommand(bb:flatbuffers.ByteBuffer, obj?:SpawnCommand):SpawnCommand {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SpawnCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():EntityTexture {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : EntityTexture.BabySlime1;
}

pos(obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Vec2()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startSpawnCommand(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addType(builder:flatbuffers.Builder, type:EntityTexture) {
  builder.addFieldInt8(0, type, EntityTexture.BabySlime1);
}

static addPos(builder:flatbuffers.Builder, posOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, posOffset, 0);
}

static endSpawnCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
