// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Vec2 } from '../../wrath-of-toldir/vec2';


export class MagicAttack {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):MagicAttack {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMagicAttack(bb:flatbuffers.ByteBuffer, obj?:MagicAttack):MagicAttack {
  return (obj || new MagicAttack()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMagicAttack(bb:flatbuffers.ByteBuffer, obj?:MagicAttack):MagicAttack {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MagicAttack()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

targetKey():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

targetPos(obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Vec2()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startMagicAttack(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTargetKey(builder:flatbuffers.Builder, targetKey:number) {
  builder.addFieldInt32(0, targetKey, 0);
}

static addTargetPos(builder:flatbuffers.Builder, targetPosOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, targetPosOffset, 0);
}

static endMagicAttack(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
