// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class NormalAttack {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):NormalAttack {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNormalAttack(bb:flatbuffers.ByteBuffer, obj?:NormalAttack):NormalAttack {
  return (obj || new NormalAttack()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNormalAttack(bb:flatbuffers.ByteBuffer, obj?:NormalAttack):NormalAttack {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NormalAttack()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

facing():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startNormalAttack(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addFacing(builder:flatbuffers.Builder, facing:number) {
  builder.addFieldInt8(0, facing, 0);
}

static endNormalAttack(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createNormalAttack(builder:flatbuffers.Builder, facing:number):flatbuffers.Offset {
  NormalAttack.startNormalAttack(builder);
  NormalAttack.addFacing(builder, facing);
  return NormalAttack.endNormalAttack(builder);
}
}
