// automatically generated by the FlatBuffers compiler, do not modify

import { DamageComponent } from '../../wrath-of-toldir/items/damage-component';


export enum Component{
  NONE = 0,
  DamageComponent = 1
}

export function unionToComponent(
  type: Component,
  accessor: (obj:DamageComponent) => DamageComponent|null
): DamageComponent|null {
  switch(Component[type]) {
    case 'NONE': return null; 
    case 'DamageComponent': return accessor(new DamageComponent())! as DamageComponent;
    default: return null;
  }
}

export function unionListToComponent(
  type: Component, 
  accessor: (index: number, obj:DamageComponent) => DamageComponent|null, 
  index: number
): DamageComponent|null {
  switch(Component[type]) {
    case 'NONE': return null; 
    case 'DamageComponent': return accessor(index, new DamageComponent())! as DamageComponent;
    default: return null;
  }
}

