// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ItemQuality } from '../../wrath-of-toldir/items/item-quality';


export class QualityComponent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):QualityComponent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsQualityComponent(bb:flatbuffers.ByteBuffer, obj?:QualityComponent):QualityComponent {
  return (obj || new QualityComponent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsQualityComponent(bb:flatbuffers.ByteBuffer, obj?:QualityComponent):QualityComponent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new QualityComponent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

quality():ItemQuality {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ItemQuality.Normal;
}

static startQualityComponent(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addQuality(builder:flatbuffers.Builder, quality:ItemQuality) {
  builder.addFieldInt8(0, quality, ItemQuality.Normal);
}

static endQualityComponent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createQualityComponent(builder:flatbuffers.Builder, quality:ItemQuality):flatbuffers.Offset {
  QualityComponent.startQualityComponent(builder);
  QualityComponent.addQuality(builder, quality);
  return QualityComponent.endQualityComponent(builder);
}
}
