// automatically generated by the FlatBuffers compiler, do not modify

export enum HeroTexture{
  Hero1 = 0,
  Hero2 = 1,
  Hero3 = 2,
  Hero4 = 3,
  Hero5 = 4,
  Hero6 = 5,
  Hero7 = 6,
  Hero8 = 7,
  Hero9 = 8,
  Hero10 = 9
}

