// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class MapChangedEvent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):MapChangedEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMapChangedEvent(bb:flatbuffers.ByteBuffer, obj?:MapChangedEvent):MapChangedEvent {
  return (obj || new MapChangedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMapChangedEvent(bb:flatbuffers.ByteBuffer, obj?:MapChangedEvent):MapChangedEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MapChangedEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startMapChangedEvent(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static endMapChangedEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMapChangedEvent(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset):flatbuffers.Offset {
  MapChangedEvent.startMapChangedEvent(builder);
  MapChangedEvent.addId(builder, idOffset);
  return MapChangedEvent.endMapChangedEvent(builder);
}
}
