name = "wrath-of-toldir-server-dev"
type = "javascript"

account_id = ""
workers_dev = true
# route = ""
# zone_id = ""

compatibility_date = "2022-03-12"
compatibility_flags = []

[durable_objects]
bindings = [
  { name = "MAP", class_name = "Map" },
  { name = "COMBAT", class_name = "Combat" }
]

[build]
command = "yarn build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"

[miniflare]
durable_objects_persist = true

[[migrations]]
tag = "v1"
new_classes = ["Map", "Combat"]

[vars]
FRONTEND_URI="http://192.168.1.40:8080"

[env.production]
name = "wrath-of-toldir-server"
vars = { FRONTEND_URI = "https://wot.jasoncabot.com" }

[env.production.durable_objects]
bindings = [
  { name = "MAP", class_name = "Map" },
  { name = "COMBAT", class_name = "Combat" }
]

[[env.production.migrations]]
tag = "v1"
new_classes = ["Map", "Combat"]
