name = "wrath-of-toldir-server-dev"
type = "javascript"

account_id = ""
workers_dev = true

compatibility_date = "2022-03-12"
compatibility_flags = []

[durable_objects]
bindings = [
  { name = "MAP", class_name = "Map" },
  { name = "COMBAT", class_name = "Combat" },
  { name = "CHARACTER", class_name = "Character" },
  { name = "ITEM", class_name = "Item" }
]

[build]
command = "yarn build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"

[miniflare]
durable_objects_persist = true

[[migrations]]
tag = "v1"
new_classes = ["Map"]

[[migrations]]
tag = "v2"
new_classes = ["Combat"]

[[migrations]]
tag = "v3"
new_classes = ["Character"]

[[migrations]]
tag = "v4"
new_classes = ["Item"]

[vars]
FRONTEND_URI="http://0.0.0.0:8080"

[env.production]
name = "wrath-of-toldir-server"
vars = { FRONTEND_URI = "https://wot.jasoncabot.com" }

[env.production.durable_objects]
bindings = [
  { name = "MAP", class_name = "Map" },
  { name = "COMBAT", class_name = "Combat" },
  { name = "CHARACTER", class_name = "Character" },
  { name = "ITEM", class_name = "Item" },
]

[[env.production.migrations]]
tag = "v1"
new_classes = ["Map"]

[[env.production.migrations]]
tag = "v2"
new_classes = ["Combat"]

[[env.production.migrations]]
tag = "v3"
new_classes = ["Character"]

[[env.production.migrations]]
tag = "v4"
new_classes = ["Item"]
