// automatically generated by the FlatBuffers compiler, do not modify

import { MagicAttack } from '../../wrath-of-toldir/attacks/magic-attack';
import { NormalAttack } from '../../wrath-of-toldir/attacks/normal-attack';


export enum AttackData{
  NONE = 0,
  NormalAttack = 1,
  MagicAttack = 2
}

export function unionToAttackData(
  type: AttackData,
  accessor: (obj:MagicAttack|NormalAttack) => MagicAttack|NormalAttack|null
): MagicAttack|NormalAttack|null {
  switch(AttackData[type]) {
    case 'NONE': return null; 
    case 'NormalAttack': return accessor(new NormalAttack())! as NormalAttack;
    case 'MagicAttack': return accessor(new MagicAttack())! as MagicAttack;
    default: return null;
  }
}

export function unionListToAttackData(
  type: AttackData, 
  accessor: (index: number, obj:MagicAttack|NormalAttack) => MagicAttack|NormalAttack|null, 
  index: number
): MagicAttack|NormalAttack|null {
  switch(AttackData[type]) {
    case 'NONE': return null; 
    case 'NormalAttack': return accessor(index, new NormalAttack())! as NormalAttack;
    case 'MagicAttack': return accessor(index, new MagicAttack())! as MagicAttack;
    default: return null;
  }
}

