// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class AttackCommand {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):AttackCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAttackCommand(bb:flatbuffers.ByteBuffer, obj?:AttackCommand):AttackCommand {
  return (obj || new AttackCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAttackCommand(bb:flatbuffers.ByteBuffer, obj?:AttackCommand):AttackCommand {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AttackCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startAttackCommand(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endAttackCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAttackCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  AttackCommand.startAttackCommand(builder);
  return AttackCommand.endAttackCommand(builder);
}
}
