// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class AttackCommand {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):AttackCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAttackCommand(bb:flatbuffers.ByteBuffer, obj?:AttackCommand):AttackCommand {
  return (obj || new AttackCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAttackCommand(bb:flatbuffers.ByteBuffer, obj?:AttackCommand):AttackCommand {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AttackCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

facing():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : 0;
}

static startAttackCommand(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addFacing(builder:flatbuffers.Builder, facing:number) {
  builder.addFieldInt8(0, facing, 0);
}

static endAttackCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAttackCommand(builder:flatbuffers.Builder, facing:number):flatbuffers.Offset {
  AttackCommand.startAttackCommand(builder);
  AttackCommand.addFacing(builder, facing);
  return AttackCommand.endAttackCommand(builder);
}
}
