// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Action, unionToAction, unionListToAction } from '../../wrath-of-toldir/commands/action';


export class Command {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):Command {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCommand(bb:flatbuffers.ByteBuffer, obj?:Command):Command {
  return (obj || new Command()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCommand(bb:flatbuffers.ByteBuffer, obj?:Command):Command {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Command()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

seq():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

actionType():Action {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Action.NONE;
}

action<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startCommand(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addSeq(builder:flatbuffers.Builder, seq:number) {
  builder.addFieldInt32(0, seq, 0);
}

static addActionType(builder:flatbuffers.Builder, actionType:Action) {
  builder.addFieldInt8(1, actionType, Action.NONE);
}

static addAction(builder:flatbuffers.Builder, actionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, actionOffset, 0);
}

static endCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishCommandBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedCommandBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createCommand(builder:flatbuffers.Builder, seq:number, actionType:Action, actionOffset:flatbuffers.Offset):flatbuffers.Offset {
  Command.startCommand(builder);
  Command.addSeq(builder, seq);
  Command.addActionType(builder, actionType);
  Command.addAction(builder, actionOffset);
  return Command.endCommand(builder);
}
}
