// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class LeaveCommand {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):LeaveCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLeaveCommand(bb:flatbuffers.ByteBuffer, obj?:LeaveCommand):LeaveCommand {
  return (obj || new LeaveCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLeaveCommand(bb:flatbuffers.ByteBuffer, obj?:LeaveCommand):LeaveCommand {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LeaveCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startLeaveCommand(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endLeaveCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLeaveCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  LeaveCommand.startLeaveCommand(builder);
  return LeaveCommand.endLeaveCommand(builder);
}
}
