name: Deploy Cloudflare Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Server Dependencies
        run: yarn
        working-directory: ./server

      - name: Compile FlatBuffer
        run: |
          # "These are committed but just in case you forget how to generate them..."
          # flatc -o ./client/src/models/ --ts ./shared/flatbuffers/*.fbs --ts
          # flatc -o ./server/src/models/ --ts ./shared/flatbuffers/*.fbs --ts

      - name: Deploy Server
        uses: cloudflare/wrangler-action@next
        with:
          workingDirectory: ./server
          environment: production
          apiToken: ${{ secrets.CF_API_TOKEN }}
